{"name": "test_unsuccessfull_create_order_without_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_create_order.TestCreateOrder object at 0x00000148D16C9810>\nclient = <src.requests.requests.Request object at 0x00000148D1985A90>\n\n    def test_unsuccessfull_create_order_without_auth(self, client):\n            with allure.step(\"Получение списка ингредиентов\"):\n                ingredient_response = client.get(path=Path.GET_INGREDIENTS)\n                ingredient_first = ingredient_response.json()[\"data\"][0][\"_id\"]\n                ingredient_second = ingredient_response.json()[\"data\"][1][\"_id\"]\n            with allure.step(\"формирование тела запроса\"):\n                payload = {\n                    \"ingredients\": [ingredient_first, ingredient_second]\n                }\n            with allure.step(\"отправляем запрос на создание заказа и сохраняем ответ в переменную response\"):\n                response = client.post(path=Path.CREATE_ORDER, json=payload)\n            with allure.step(\"проверка кода и тела ответа\"):\n>               assert response.status_code == 401\nE               assert 200 == 401\nE                +  where 200 = <Response [200]>.status_code\n\ntests\\test_create_order.py:36: AssertionError"}, "steps": [{"name": "Получение списка ингредиентов", "status": "passed", "start": 1758999465181, "stop": 1758999465541}, {"name": "формирование тела запроса", "status": "passed", "start": 1758999465541, "stop": 1758999465541}, {"name": "отправляем запрос на создание заказа и сохраняем ответ в переменную response", "status": "passed", "start": 1758999465541, "stop": 1758999465892}, {"name": "проверка кода и тела ответа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"c:\\Users\\Dmitry\\Desktop\\Python YP\\Diplom_2\\tests\\test_create_order.py\", line 36, in test_unsuccessfull_create_order_without_auth\n    assert response.status_code == 401\n"}, "start": 1758999465892, "stop": 1758999465892}], "start": 1758999465181, "stop": 1758999465894, "uuid": "dcc4d06c-2c71-4657-b9f2-17294abeccf2", "historyId": "5d97aac89787e49dbd21585920b96ef0", "testCaseId": "5d97aac89787e49dbd21585920b96ef0", "fullName": "tests.test_create_order.TestCreateOrder#test_unsuccessfull_create_order_without_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-A445VSF"}, {"name": "thread", "value": "4744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}], "titlePath": ["tests", "test_create_order.py", "TestCreateOrder"]}